version: '3'
services:

  #MySQL Service
  db:
    volumes:
      - bd_jwtand:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    image: mysql:8
    container_name: db_jwtand
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_jwtand
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  bd_jwtand:
    driver: local